schema: https://vercel.saleor.cloud/graphql/
documents: graphql/**/*.graphql
extensions:
  codegen:
    overwrite: true
    generates:
      generated/graphql.ts:
        plugins:
          - typescript
          - typescript-operations
          - urql-introspection
          - typescript-urql
