schema: ${SCHEMA_ENDPOINT:"https://vercel.saleor.cloud/graphql/"}
documents: graphql/**/*.graphql
extensions:
  codegen:
    overwrite: true
    generates:
      generated/graphql.ts:
        plugins:
          - typescript
          - typescript-operations
          - urql-introspection
          - typescript-urql
        config:
          scalars:
            JSONString: string
            UUID: string
          dedupeOperationSuffix: true # Prevent suffix duplication in generated names
